# Generated by Django 4.0.3 on 2022-04-07 06:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cust_onboard', '0002_alter_order_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cust_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
